# Configuration for converting your website to markdown
input_dir: "/path/to/your/website"  # Replace with your website directory path
output_dir: "./converted_site"      # Output directory for markdown files

# Content selection
content_selector: "div.main-content"  # Adjust this to match your site's main content container
exclude_selectors:  # Elements to exclude
  - "header"
  - "footer"
  - "nav"
  - "div.sidebar"
  - "div.navigation"
  - "div.menu"
  - "div.advertisement"

# Content preservation options
preserve_links: true
preserve_images: true

# Processing options
max_depth: 5  # Adjust based on your site's depth 