# HTML to Markdown Extractor Configuration

# Input and output directories
input_dir: "./html_files"
output_dir: "./markdown_output"

# Content selection
content_selector: "div.main-content"  # CSS selector for main content container
exclude_selectors:  # CSS selectors for content to exclude
  - "div.navigation"
  - "header"
  - "footer"
  - "div.sidebar"

# Content preservation options
preserve_links: true
preserve_images: true

# Processing options
max_depth: 3  # Maximum directory depth to process (optional) 